### PR TITLE
i hate jack

### PR DESCRIPTION
**Pull request by Keenan-Nicholson**
i hate jack and i didnt test this and idk if it works but it looks like it should i hate him so much

### CODE REVIEW

**Review by nint8835 — CHANGES_REQUESTED** [review]
This will not work without adding a corresponding cron trigger to the wrangler config. Also this'll be telling Jack to get up at either 4:30 or 5:30 in the morning, not sure if that's your intention

**Comment by Keenan-Nicholson** [comment]
I dont understand ur big word fancy man

**Comment by nint8835** [comment]
https://github.com/nint8835/gramfel/blob/main/wrangler.toml

**Comment by Keenan-Nicholson** [comment]
what time zone is this shit in why is it 4:30 wtf

**Comment by nint8835** [comment]
UTC

**Review by nint8835 — APPROVED** [review]

**Pull request merged**
